DROP FUNCTION `ucfirst`;
DELIMITER ;;
CREATE FUNCTION `ucfirst` (`str` text) RETURNS text CHARACTER SET 'utf8'
NO SQL
    DETERMINISTIC
BEGIN
RETURN CONCAT(UPPER(SUBSTRING(str, 1, 1)), LOWER(SUBSTRING(str, 2)));
END;;
DELIMITER ;